version: '2'
services:
  neo4j:
    image: neo4j:5.19
    x-kubernetes:
      imagePullPolicy: IfNotPresent
    environment:
      - NEO4J_PLUGINS= ["apoc", "n10s"]
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_dbms_memory_heap_max__size=8G
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_server_config_strict__validation_enabled=false
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - ./data/neo4j:/data
    networks:
      internal:
        aliases:
          - neo4j
  kg:
    build: .
    image: maayanlab/knowledge_graph:latest
    env_file: .env
    ports:
      - 3001:3000
# Internal docker networks
networks:
  internal:
